### PR TITLE
grammar & style changes for native fluency

### PR DESCRIPTION
**Pull request by brandondrew**
I tried to keep things as close to the original as possible, while still making it sound natural and idiomatic to a native English speaker.

### CODE REVIEW

**Comment by steveklabnik** [comment]
LGTM. I don't know what @d-unseductable 's policy is on merge commits, so I won't merge this just yet.

**Comment by d-unseductable** [comment]
Hey @brandondrew! Thank you very much! I think that good looking and grammatically correct docs are as important as a clean codebase 👍

**Comment by d-unseductable** [comment]
@steveklabnik, feel free to merge any PR here if you see that it's good!

**Comment by brandondrew** [comment]
You're welcome, and it's my pleasure.  This project looks awesome, so I'm happy to help any way I can (and can find time for).

Sorry about it being a merge commit—that was due to accidentally first creating a PR for my own fork, rather than the main repo.

**Pull request merged**
