### PR TITLE
Refactor &str to CString conversions

### PR DESCRIPTION
**Pull request by d-unseductable**
- Create `util::str_to_cstring` function

@steveklabnik, a small clean up for the hacking session #4 😄 

Trying to DRY up the `CString` handling. Similar approach worked fine for `Vec -> ptr` conversions (1b9932904646741229a683d86a0e7761ab02a41f)

### CODE REVIEW

**Comment by steveklabnik** [comment]
So, I have some concerns this still won't work. I am about to step out, but I will try it on my machine to check.

```rust
str_to_cstring(name).as_ptr(),
```

So, because this ends up being a temporary, I'm not sure if it gets destroyed before the call is over. I can see that it might not, but I can see that it might, as well.

**Comment by steveklabnik** [comment]
Seems to work fine. :+1:

**Comment by d-unseductable** [comment]
Should work fine, just tested with [dummy `CString` implementation + `Drop` trait](https://play.rust-lang.org/?gist=c46a06a443a5822d92425627cb8949e5&version=stable&backtrace=0)

In this case pointer does not outlive the string unlike the first implementation 😄

**Comment by steveklabnik** [comment]
Yeah, I just always get a bit suspicious with temporaries :)

**Pull request merged**
